name: Generate SHA256 Checksums

on:
  release:
    types: [published]
  workflow_dispatch: #

jobs:
  generate-checksums:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Release Assets
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fileName: "*.7z"

      - name: Calculate SHA256 Checksum
        id: checksum
        run: |
          set -e

          # Get the latest Git tag
          git fetch --tags
          RELEASE_TAG="$(git describe --tags $(git rev-list --tags --max-count=1))"

          echo "RELEASE_TAG: $RELEASE_TAG"
          RELEASE_TAG_NO_V="${RELEASE_TAG#v}"
          echo "RELEASE_TAG_NO_V=${RELEASE_TAG_NO_V}" >> $GITHUB_ENV

          CHECKSUMS_FILE="${RELEASE_TAG_NO_V}-checksums-sha256.txt"

          # Move to asset download directory
          cd /home/runner/work/${{ github.repository }}/$(basename ${{ github.repository }})

          for file in *.7z; do
            sha256sum "$file" >> "$CHECKSUMS_FILE"
          done

          echo "Checksum file created: $CHECKSUMS_FILE"
          cat "$CHECKSUMS_FILE"

      - name: Upload Checksum File to Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.RELEASE_TAG_NO_V }}-checksums-sha256.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
